name: Scala CI

on:
  push:
    branches: [ main, setup/* ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{ secrets.gitlab_fit_token }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Install dependencies
      run: sudo apt install -y swig4.0 ant
    - name: Build native dependencies
      run: sbt buildNativeDeps
    - name: Run tests
      run: sbt test
